export const db = [
  {
    name: "Jaime Méndez",
    materias: [
      {
        name: "Autonomia",
        course: null,
        start: "15/01/2024",
        end: "26/06/2024",
        carr: "SEC",
        sem: null,
        sec: null,
        hours_prog: null,
        hours_real: 14,
        clasif: "B",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "María del Rocío García",
    materias: [
      {
        name: "Metodos Estadisiticos",
        course: "DDE-2103",
        start: "04/08/2023",
        end: "15/12/2023",
        carr: "DDE",
        sem: "2",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Metodología de la Investigación 3 4",
        course: "DDE-3102 4101",
        start: "05/08/2023",
        end: "16/12/2023",
        carr: "DDE",
        sem: "3 4",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "Héctor Sánchez Tamayo",
    materias: [
      {
        name: "Desarrollo de Organizaciones",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Gestión de la Calidad",
        course: "ISN-INI6106",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "6",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Información",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Fisica",
        course: "BD-FIS209",
        start: "12/02/2024",
        end: "15/03/2024",
        carr: "BACHD",
        sem: null,
        sec: null,
        hours_prog: 50,
        hours_real: 50,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "Jaime Villavicencio",
    materias: [
      {
        name: "Autonomia",
        course: null,
        start: "15/01/2024",
        end: "26/06/2024",
        carr: "SEC",
        sem: null,
        sec: null,
        hours_prog: null,
        hours_real: 14,
        clasif: "B",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "María Aguilar",
    materias: [
      {
        name: "Metodos Estadisiticos",
        course: "DDE-2103",
        start: "04/08/2023",
        end: "15/12/2023",
        carr: "DDE",
        sem: "2",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Metodología de la Investigación 3 4",
        course: "DDE-3102 4101",
        start: "05/08/2023",
        end: "16/12/2023",
        carr: "DDE",
        sem: "3 4",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "Héctor Velazquez",
    materias: [
      {
        name: "Desarrollo de Organizaciones",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Gestión de la Calidad",
        course: "ISN-INI6106",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "6",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Información",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Fisica",
        course: "BD-FIS209",
        start: "12/02/2024",
        end: "15/03/2024",
        carr: "BACHD",
        sem: null,
        sec: null,
        hours_prog: 50,
        hours_real: 50,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "Jaime Perez",
    materias: [
      {
        name: "Autonomia",
        course: null,
        start: "15/01/2024",
        end: "26/06/2024",
        carr: "SEC",
        sem: null,
        sec: null,
        hours_prog: null,
        hours_real: 14,
        clasif: "B",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "María Garcia",
    materias: [
      {
        name: "Metodos Estadisiticos",
        course: "DDE-2103",
        start: "04/08/2023",
        end: "15/12/2023",
        carr: "DDE",
        sem: "2",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Metodología de la Investigación 3 4",
        course: "DDE-3102 4101",
        start: "05/08/2023",
        end: "16/12/2023",
        carr: "DDE",
        sem: "3 4",
        sec: "A",
        hours_prog: 60,
        hours_real: 60,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
  {
    name: "Andrés Ibarra",
    materias: [
      {
        name: "Desarrollo de Organizaciones",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Gestión de la Calidad",
        course: "ISN-INI6106",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "6",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Sistemas de Información",
        course: "IISN-ADM8105",
        start: "19/02/2024",
        end: "20/04/2024",
        carr: "IISN",
        sem: "8",
        sec: "A",
        hours_prog: 54,
        hours_real: 27,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
      {
        name: "Fisica",
        course: "BD-FIS209",
        start: "12/02/2024",
        end: "15/03/2024",
        carr: "BACHD",
        sem: null,
        sec: null,
        hours_prog: 50,
        hours_real: 50,
        clasif: "A",
        pago: "1000",
        honorarios: "500",
      },
    ],
  },
];
